### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by jdavid** [spectraphilic/grafana-windrose#1]
- [x] Smaller inner circle
- [x] The scale on the circles can be percent (%)
- [x] Add an option to choose the number of cake bites
- [x] Add option `start`, default to 0, if below don't display
- [x] Add option for units, default to m/s
- [x] If theme is light, use black for the fonts

**Comment by johnhulth** [comment]
Just some ideas to make the wind rose more versatile...

Add option for wind vectors u, v (see definitions: http://tornado.sfsu.edu/geosciences/classes/m430/Wind/WindDirection.html)
Add options for compass directions (eg. N, E, S and W) insted of degrees .
Add option clockwise or counter clockwise.
Add option zero up or zero to the right.
Add option for different color scale (B/W?).
Add option for basic statistics eg. https://en.wikipedia.org/wiki/Wind_rose#/media/File:Wind_rose_plot.jpg and http://mesonet.agron.iastate.edu/sites/windrose.phtml?network=WI_ASOS&station=CWA

A nerdy thing would be to have an option to show wind speed in the Beaufort scale ;) see reference: https://en.wikipedia.org/wiki/Beaufort_scale

**Comment by johnhulth** [comment]
...also, the first cake bite should represent north (ei. 0 +/- X deg,) As it is now, the first cake bite start at 0 to X deg.
