### ISSUE TITLE
Windrose fails to resize to Grafana panel dimensions

### ISSUE THREAD

**Issue by hamheadless** [spectraphilic/grafana-windrose#11]
Hi there, 
Having a little trouble getting the wind rose to resize in Grafana. Is anyone else having this issue, or know how to fix it? 

Just installed Windrose on latest version of Grafana on the latest Raspbian.

![Screen Shot 2021-04-01 at 10 52 19 pm](https://user-images.githubusercontent.com/81754346/113290291-2b14be80-933d-11eb-9641-cc7c444a7e58.png)

**Comment by johanfrykebrant** [comment]
I have the same issue. 
I run grafana on Raspbian and just installed windrose in the grafana GUI.

**Comment by rossbacher** [comment]
Imho the screenshot is of https://grafana.com/grafana/plugins/fatcloud-windrose-panel/ and not of this plugin.

**Comment by jdavid** [comment]
Thanks @rossbacher , that's correct, it seems this issue was submitted to the wrong project.

**Comment by thomasvnl** [comment]
@jdavid Nice to see that you are able to respond to issues. Would be nice if you could respond to other issues in this repository too. At least make clear that you are not/do not want to maintain this repository in the README.md file as that is what it is starting to look like.

**Comment by PureTek-Innovations** [comment]
I know that this relates to another plugin, but I also have the same problem with it.
Did anyone find a solution?
Thanks
