### ISSUE TITLE
Wind rose doesn't want to render when all speed values are zero

### ISSUE THREAD

**Issue by thomasvnl** [spectraphilic/grafana-windrose#15]
Hi,

I have a situation in which during a small window of time (say 15 minutes) all speed values are zero. At this point the wind rose fails to render even though there is valid data. The direction is set, but the speed is just zero. When I change my time range and speeds higher than zero are recorded, the wind rose renders. It also freezes during resize when a newly selected time range again includes only zero speed values.

To me this seems to be a bug because it is not uncommon on quiet nights that there is relatively no wind (depending on the resolution of your measuring equipment of course).

I have been using this plugin for the past week and other than this one issue I can only say thank you for creating a Grafana 8.x.x compatible wind rose that looks really smart 👍.

Cheers,
Thomas

**Comment by pbousek** [comment]
Grafana 11.x, data source prometheus - same behaviour - when during selected time period are all wind speed 0, than I got this 
![image](https://github.com/spectraphilic/grafana-windrose/assets/21953786/df3e4956-261a-484d-ac8d-9992b29645b2)
