### ISSUE TITLE
Use of windrose in Open source context 

### ISSUE THREAD

**Issue by michael-gollan** [spectraphilic/grafana-windrose#25]
Hello,

we really like your plugin and would like to use it in the context of a citizen science project. 
Could you please add a Open Source license like:
 GNU GPL 3.0 to it?

https://www.gnu.org/licenses/gpl-3.0.txt 

You may just put the attached license file in your project:
[LICENSE.txt](https://github.com/spectraphilic/grafana-windrose/files/10259685/LICENSE.txt)

Thx and best Regards
Michael

**Comment by jdavid** [comment]
@ArcticSnow What licence should we use for this?

**Comment by jdavid** [comment]
Okay, I have put the GPL v3 as suggested, I think it's a good one for this repo.
