### ISSUE TITLE
This plugin uses a deprecated, legacy platform based on AngularJS

### ISSUE THREAD

**Issue by raindancer2204** [spectraphilic/grafana-windrose#27]
Hi, I want to display my weather data via Grafana 10.1.2 and came across your Windrosen plugin.

I integrated it cleanly into my Docker container and but I get the message in the Gui:

![grafik](https://github.com/spectraphilic/grafana-windrose/assets/49243048/effbf609-e3d0-4c1f-a481-59077cb41dc6)

![grafik](https://github.com/spectraphilic/grafana-windrose/assets/49243048/4e532728-9b66-483d-a4d1-3847c9896ba2)

My question is, are you planning a modification here because according to the GUI, AngularJS is not supported in the next releases?

Thank you

**Comment by jdavid** [comment]
Hi, I've an instance of Grafana v9.2 with the Windrose plugin. I'll eventually upgrade and fix the plugin, but I don't have specific plans, probably some time next year. Otherwise PRs are wellcome.
Best
